<?php
$z[0]=Array("global","",110,140);
$z[0][4]=array();
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",230,251);
$z[1][4]=array();
$z[1][4]['name']="cfg_xm";
$z[2]=Array("global","",271,294);
$z[2][4]=array();
$z[2][4]['name']="cfg_txqq";
$z[3]=Array("global","",563,589);
$z[3][4]=array();
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",592,616);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";

?>