<?php
$z[0]=Array("global","",295,316);
$z[0][4]=array();
$z[0][4]['name']="cfg_xm";
$z[1]=Array("global","",358,379);
$z[1][4]=array();
$z[1][4]['name']="cfg_js";
$z[2]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img width='80' height='60' src='{@me['litpic']}' class='icon wp-post-image' alt='{@me['title']}' title='{@me['title']}' />\"); [/field:array] </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function=\"MyDate('Y/m/d',@me)\"/] </span> </div>\r\n        </li>\r\n        ",622,1227);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['titlelen']="100";
$z[2][4]['typeid']="6,8,1";
$z[3]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img width='80' height='60' src='{@me['litpic']}' class='icon wp-post-image' alt='{@me['title']}' title='{@me['title']}' />\"); [/field:array] </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function=\"MyDate('Y/m/d',@me)\"/] </span> </div>\r\n        </li>\r\n        ",1434,2040);
$z[3][4]=array();
$z[3][4]['row']="5";
$z[3][4]['titlelen']="100";
$z[3][4]['typeid']="6,8,1";
$z[4]=Array("flink","\r\n        <li>[field:link /]</li>\r\n        ",2261,2363);
$z[4][4]=array();
$z[4][4]['titlelen']="16";
$z[4][4]['row']="6";
$z[4][4]['type']="text";

?>